package io.github.kylinlee.chatsim.ui.theme

import androidx.compose.ui.graphics.Color

val FallbackPrimary = Color(0xFF8F4C38)
val FallbackOnPrimary = Color(0xFFFFFFFF)
val FallbackPrimaryContainer = Color(0xFFFFDBD1)
val FallbackOnPrimaryContainer = Color(0xFF3A0B01)
val FallbackSecondary = Color(0xFF77574E)
val FallbackOnSecondary = Color(0xFFFFFFFF)
val FallbackSecondaryContainer = Color(0xFFFFDBD1)
val FallbackOnSecondaryContainer = Color(0xFF2C150F)
val FallbackTertiary = Color(0xFF6C5D2F)
val FallbackOnTertiary = Color(0xFFFFFFFF)
val FallbackTertiaryContainer = Color(0xFFF5E1A7)
val FallbackOnTertiaryContainer = Color(0xFF231B00)
val FallbackError = Color(0xFFBA1A1A)
val FallbackOnError = Color(0xFFFFFFFF)
val FallbackErrorContainer = Color(0xFFFFDAD6)
val FallbackOnErrorContainer = Color(0xFF410002)
val FallbackBackground = Color(0xFFFFFBFF)
val FallbackOnBackground = Color(0xFF201A18)
val FallbackSurface = Color(0xFFFFFBFF)
val FallbackOnSurface = Color(0xFF201A18)
val FallbackSurfaceVariant = Color(0xFFF5DED8)
val FallbackOnSurfaceVariant = Color(0xFF53433F)
val FallbackOutline = Color(0xFF85736E)

val FallbackPrimaryDark = Color(0xFFFFB5A0)
val FallbackOnPrimaryDark = Color(0xFF561F0F)
val FallbackPrimaryContainerDark = Color(0xFF723523)
val FallbackOnPrimaryContainerDark = Color(0xFFFFDBD1)
val FallbackSecondaryDark = Color(0xFFE7BDB2)
val FallbackOnSecondaryDark = Color(0xFF442A22)
val FallbackSecondaryContainerDark = Color(0xFF5D4037)
val FallbackOnSecondaryContainerDark = Color(0xFFFFDBD1)
val FallbackTertiaryDark = Color(0xFFD8C58D)
val FallbackOnTertiaryDark = Color(0xFF3B2F05)
val FallbackTertiaryContainerDark = Color(0xFF534619)
val FallbackOnTertiaryContainerDark = Color(0xFFF5E1A7)
val FallbackErrorDark = Color(0xFFFFB4AB)
val FallbackOnErrorDark = Color(0xFF690005)
val FallbackErrorContainerDark = Color(0xFF93000A)
val FallbackOnErrorContainerDark = Color(0xFFFFDAD6)
val FallbackBackgroundDark = Color(0xFF201A18)
val FallbackOnBackgroundDark = Color(0xFFEDE0DD)
val FallbackSurfaceDark = Color(0xFF201A18)
val FallbackOnSurfaceDark = Color(0xFFEDE0DD)
val FallbackSurfaceVariantDark = Color(0xFF53433F)
val FallbackOnSurfaceVariantDark = Color(0xFFD8C2BC)
val FallbackOutlineDark = Color(0xFFA08C87)
